#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
###########################################################################
# Copyright © 1998 - 2026 Tencent. All Rights Reserved.
###########################################################################
"""
Author: Tencent AI Arena Authors

Monitor panel configuration builder for Robot Vacuum.
清扫大作战监控面板配置构建器。
"""


from kaiwudrl.common.monitor.monitor_config_builder import MonitorConfigBuilder


def build_monitor():
    """
    # This function is used to create monitoring panel configurations for custom indicators.
    # 该函数用于创建自定义指标的监控面板配置。
    """
    monitor = MonitorConfigBuilder()

    config_dict = (
        monitor.title("清扫大作战")
        .add_group(
            group_name="训练健康",
            group_name_en="training_health",
        )
        .add_panel(
            name="批次奖励",
            name_en="batch_reward",
            type="line",
        )
        .add_metric(
            metrics_name="batch_reward",
            expr="avg(batch_reward{})",
        )
        .end_panel()
        .add_panel(
            name="总损失",
            name_en="total_loss",
            type="line",
        )
        .add_metric(
            metrics_name="total_loss",
            expr="avg(total_loss{})",
        )
        .end_panel()
        .add_panel(
            name="价值损失",
            name_en="value_loss",
            type="line",
        )
        .add_metric(
            metrics_name="value_loss",
            expr="avg(value_loss{})",
        )
        .end_panel()
        .add_panel(
            name="策略损失",
            name_en="policy_loss",
            type="line",
        )
        .add_metric(
            metrics_name="policy_loss",
            expr="avg(policy_loss{})",
        )
        .end_panel()
        .add_panel(
            name="熵损失",
            name_en="entropy_loss",
            type="line",
        )
        .add_metric(
            metrics_name="entropy_loss",
            expr="avg(entropy_loss{})",
        )
        .end_panel()
        .end_group()
        .add_group(
            group_name="训练阶段",
            group_name_en="training_stage",
        )
        .add_panel(
            name="当前训练阶段",
            name_en="training_stage_id",
            type="line",
        )
        .add_metric(
            metrics_name="training_stage_id",
            expr="avg(training_stage_id{})",
        )
        .end_panel()
        .add_panel(
            name="当前生效训练阶段",
            name_en="active_training_stage_id",
            type="line",
        )
        .add_metric(
            metrics_name="active_training_stage_id",
            expr="avg(active_training_stage_id{})",
        )
        .end_panel()
        .add_panel(
            name="训练阶段指示",
            name_en="training_stage_indicator",
            type="line",
        )
        .add_metric(
            metrics_name="training_stage_early",
            expr="avg(training_stage_early{})",
        )
        .add_metric(
            metrics_name="training_stage_middle",
            expr="avg(training_stage_middle{})",
        )
        .add_metric(
            metrics_name="training_stage_late",
            expr="avg(training_stage_late{})",
        )
        .end_panel()
        .add_panel(
            name="生效阶段指示",
            name_en="active_training_stage_indicator",
            type="line",
        )
        .add_metric(
            metrics_name="active_training_stage_early",
            expr="avg(active_training_stage_early{})",
        )
        .add_metric(
            metrics_name="active_training_stage_middle",
            expr="avg(active_training_stage_middle{})",
        )
        .add_metric(
            metrics_name="active_training_stage_late",
            expr="avg(active_training_stage_late{})",
        )
        .end_panel()
        .end_group()
        .add_group(
            group_name="模型效果",
            group_name_en="evaluation",
        )
        .add_panel(
            name="整局回报均值",
            name_en="episode_return_mean",
            type="line",
        )
        .add_metric(
            metrics_name="episode_return_mean",
            expr="avg(episode_return_mean{})",
        )
        .end_panel()
        .add_panel(
            name="完成率",
            name_en="completed_rate",
            type="line",
        )
        .add_metric(
            metrics_name="completed_rate",
            expr="avg(completed_rate{})",
        )
        .end_panel()
        .add_panel(
            name="没电率",
            name_en="battery_depleted_rate",
            type="line",
        )
        .add_metric(
            metrics_name="battery_depleted_rate",
            expr="avg(battery_depleted_rate{})",
        )
        .end_panel()
        .add_panel(
            name="首充成功率",
            name_en="first_charge_success_rate",
            type="line",
        )
        .add_metric(
            metrics_name="first_charge_success_rate",
            expr="avg(first_charge_success_rate{})",
        )
        .end_panel()
        .add_panel(
            name="清扫比例均值",
            name_en="clean_ratio_mean",
            type="line",
        )
        .add_metric(
            metrics_name="clean_ratio_mean",
            expr="avg(clean_ratio_mean{})",
        )
        .end_panel()
        .end_group()
        .add_group(
            group_name="回桩质量",
            group_name_en="charge_quality",
        )
        .add_panel(
            name="首次充电步数均值",
            name_en="first_charge_step_mean",
            type="line",
        )
        .add_metric(
            metrics_name="first_charge_step_mean",
            expr="avg(first_charge_step_mean{})",
        )
        .end_panel()
        .add_panel(
            name="回桩触发裕量均值",
            name_en="return_trigger_margin_mean",
            type="line",
        )
        .add_metric(
            metrics_name="return_trigger_margin_mean",
            expr="avg(return_trigger_margin_mean{})",
        )
        .end_panel()
        .add_panel(
            name="回桩路径命中率",
            name_en="charge_route_found_rate_weighted",
            type="line",
        )
        .add_metric(
            metrics_name="charge_route_found_rate_weighted",
            expr="avg(charge_route_found_rate_weighted{})",
        )
        .end_panel()
        .add_panel(
            name="贴桩未充平均次数",
            name_en="dock_contact_without_charge_mean",
            type="line",
        )
        .add_metric(
            metrics_name="dock_contact_without_charge_mean",
            expr="avg(dock_contact_without_charge_mean{})",
        )
        .end_panel()
        .add_panel(
            name="进入近桩区比率",
            name_en="near_dock_entry_rate",
            type="line",
        )
        .add_metric(
            metrics_name="near_dock_entry_rate",
            expr="avg(near_dock_entry_rate{})",
        )
        .end_panel()
        .add_panel(
            name="贴桩后成功充电率",
            name_en="dock_success_given_contact_rate",
            type="line",
        )
        .add_metric(
            metrics_name="dock_success_given_contact_rate",
            expr="avg(dock_success_given_contact_rate{})",
        )
        .end_panel()
        .add_panel(
            name="近桩停滞步数均值",
            name_en="dock_stall_steps_mean",
            type="line",
        )
        .add_metric(
            metrics_name="dock_stall_steps_mean",
            expr="avg(dock_stall_steps_mean{})",
        )
        .end_panel()
        .add_panel(
            name="近桩回退次数均值",
            name_en="dock_regress_count_mean",
            type="line",
        )
        .add_metric(
            metrics_name="dock_regress_count_mean",
            expr="avg(dock_regress_count_mean{})",
        )
        .end_panel()
        .add_panel(
            name="贴桩后成功充电步数均值",
            name_en="charge_success_after_dock_step_mean",
            type="line",
        )
        .add_metric(
            metrics_name="charge_success_after_dock_step_mean",
            expr="avg(charge_success_after_dock_step_mean{})",
        )
        .end_panel()
        .add_panel(
            name="回桩卡顿步数均值",
            name_en="route_stall_steps_total_mean",
            type="line",
        )
        .add_metric(
            metrics_name="route_stall_steps_total_mean",
            expr="avg(route_stall_steps_total_mean{})",
        )
        .end_panel()
        .end_group()
        .add_group(
            group_name="失败归因",
            group_name_en="failure_breakdown",
        )
        .add_panel(
            name="撞 NPC 率",
            name_en="npc_collision_rate",
            type="line",
        )
        .add_metric(
            metrics_name="npc_collision_rate",
            expr="avg(npc_collision_rate{})",
        )
        .end_panel()
        .add_panel(
            name="异常截断率",
            name_en="abnormal_truncated_rate",
            type="line",
        )
        .add_metric(
            metrics_name="abnormal_truncated_rate",
            expr="avg(abnormal_truncated_rate{})",
        )
        .end_panel()
        .add_panel(
            name="未知失败率",
            name_en="unknown_failure_rate",
            type="line",
        )
        .add_metric(
            metrics_name="unknown_failure_rate",
            expr="avg(unknown_failure_rate{})",
        )
        .end_panel()
        .add_panel(
            name="其他失败率",
            name_en="other_failure_rate",
            type="line",
        )
        .add_metric(
            metrics_name="other_failure_rate",
            expr="avg(other_failure_rate{})",
        )
        .end_panel()
        .end_group()
        .build()
    )
    return config_dict
